packages:
  - packages/*
catalog:
  vue: ^3.5.13
  vue-tsc: 2.2.0
  vue-router: ^4.5.0
  vite: ^6.1.0
  typescript: ^5.8.3
  unbuild: ^3.3.1
  "@types/node": ^22.10.9
  eslint: ^9.20.0
  typescript-eslint: ^8.30.1
  "@eslint/js": ^9.20.0
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vitejs/plugin-vue": ^5.2.1
  ant-design-vue: ^4.2.6
  "@ant-design/icons-vue": "^7.0.1"
  vite-plugin-dts: ^4.5.0
  vitest: ^3.0.5
  "@vitest/coverage-v8": ^3.0.5
  "@vitest/ui": ^3.0.5
  "@vue/test-utils": ^2.4.6
  happy-dom: ^17.0.2
  prettier: ^3.5.0
  vxe-pc-ui: 4.3.99
  vxe-table: 4.11.15
  xe-utils: 3.5.14
  vue-component-type-helpers: ^2.2.0
  tdesign-vue-next: ^1.12.0
  dayjs: ^1.11.13
  tdesign-icons-vue-next: ^0.3.5
  element-plus: 2.10.4
