packages:
  - packages/*
catalog:
  vue: ^3.5.13
  vue-tsc: 2.1.10
  vue-router: ^4.5.0
  vite: ^6.0.11
  typescript: ^5.7.3
  unbuild: ^3.3.1
  "@types/node": ^22.10.9
  eslint: ^9.18.0
  es-toolkit: ^1.31.0
  typescript-eslint: ^8.21.0
  "@eslint/js": ^9.18.0


