packages:
  - packages/*
  - playground
catalog:
  vue: ^3.5.13
  vue-tsc: 2.2.0
  vue-router: ^4.5.0
  vite: ^6.0.11
  typescript: ^5.7.3
  unbuild: ^3.3.1
  "@types/node": ^22.10.9
  eslint: ^9.18.0
  typescript-eslint: ^8.21.0
  "@eslint/js": ^9.18.0
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vitejs/plugin-vue": ^5.2.1
  ant-design-vue: ^4.2.6
  vite-plugin-dts: ^4.5.0
  vitest: ^3.0.5
  "@vitest/coverage-v8": ^3.0.5
  "@vitest/ui": ^3.0.5
  "@vue/test-utils": ^2.4.6




