name: Changeset Check

on:
  pull_request:
    branches:
      - main

jobs:
  changeset-check:
    runs-on: ubuntu-latest
    name: Check for changeset
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project Environment
        uses: ./.github/actions/setup
        with:
          fetch-depth: 0

      - name: Check changeset status
        run: pnpm changeset status --since origin/main
