# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Setup TurboRepo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ github.sha }}
          restore-keys: turbo-

      - run: pnpm install

      - name: Generate Changelog
        id: generate-changelog
        uses: requarks/changelog-action@v1
        with:
          tag: ${{ github.ref_name }}

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          body: ${{ steps.generate-changelog.outputs.changes }}
      - run: pnpm build
      - run: pnpm pub:all
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
