name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "release-*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode (不实际发布)"
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # 获取完整的历史记录，semantic-release 需要这个
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Release all packages (dry-run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: pnpm semantic-release:all --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release all packages
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: pnpm semantic-release:all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
